//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fussball_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class verein
    {
        public verein()
        {
            this.ligas = new HashSet<liga>();
            this.spiels = new HashSet<spiel>();
            this.spiels1 = new HashSet<spiel>();
            this.spielers = new HashSet<spieler>();
        }
    
        public int V_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Liga { get; set; }
    
        public virtual ICollection<liga> ligas { get; set; }
        public virtual liga liga1 { get; set; }
        public virtual ICollection<spiel> spiels { get; set; }
        public virtual ICollection<spiel> spiels1 { get; set; }
        public virtual ICollection<spieler> spielers { get; set; }
    }
}
